# Generated by Django 5.1.3 on 2024-11-10 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
    ]
